### ISSUE TITLE
rtsp拉流，长时间运行后内存占用过大

### ISSUE THREAD

**Issue by wenjian425** [Monibuca/plugin-rtsp#10]
![image](https://user-images.githubusercontent.com/41784235/128652022-f1112295-4c46-40de-9b5a-f10c6d90b0be.png)
刚开始运行只占用1.7G左右，运行三四天之后就占用5G了

**Comment by langhuihui** [comment]
确实存在内存泄露正在优化

**Comment by langhuihui** [comment]
内存泄漏应该已经修复了
