### ISSUE TITLE
client.go在连接还没建立的时候就return，然后调用dever函数导致程序报错

### ISSUE THREAD

**Issue by lhong1001** [Monibuca/plugin-rtsp#12]
client.go  153 行  	defer client.Client.Close()

如果在连接建立前就return的话，调用client.Client.Close()会报错，可以把client.Client.Close()往后移一下；

**Comment by langhuihui** [comment]
你可以直接提PR，这样就多一个贡献者啦

**Comment by lhong1001** [comment]
没弄过，我试一下















在 2021-12-20 17:22:13，"dexter" ***@***.***> 写道：

你可以直接提PR，这样就多一个贡献者啦

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lhong1001** [comment]
提交pr了

**Comment by langhuihui** [comment]
合并了
