### ISSUE TITLE
拉流转发，服务退出

### ISSUE THREAD

**Issue by lfyppy** [Monibuca/plugin-rtsp#14]
rtsp://150.138.8.132:554/PLTV/88888888/224/3221226059/10000100000000060000000002709088_0.smil
电信iptv流 在拉流转发过程中服务退出

**Comment by langhuihui** [comment]
目前尚未支持smil格式的流

**Comment by lfyppy** [comment]
会考虑增加这部分功能吗？

**Comment by langhuihui** [comment]
如果需要的人比较多的话，会考虑的
