### ISSUE TITLE
rtsp解析出错

### ISSUE THREAD

**Issue by xiongfeigood** [Monibuca/plugin-rtsp#18]
你好，请问我们有一款相机用VLC都能正常播放，用程序拉流，报错：
Describe:rtsp://admin:admin@10.1.1.71:8557/h264 error:sdp: invalid value `vzinfo` (m=vzinfo 0 RTP/AVP 108)
请问大神能否兼容这种相机呢？

**Comment by xiongfeigood** [comment]
估计是相机方自己弄了个自定义的名称导致解析出错，不知道能否兼容

**Comment by langhuihui** [comment]
确实是这个原因

**Comment by xiongfeigood** [comment]
请问可以兼容吗

**Comment by langhuihui** [comment]
主要是这个依赖第三方库实现的，要兼容起来就比较麻烦了
