### ISSUE TITLE
rtsp拉流成功一段时间以后报500错误，摄像头黑屏

### ISSUE THREAD

**Issue by lhong1001** [Monibuca/plugin-rtsp#19]
2022/02/17 15:56:33 RTSP/1.0 200 OK
CSeq: 3
Content-Base: rtsp://172.16.9.137:554/H264/ch1/sub/av_stream/
Content-Length: 639
Content-Type: application/sdp

v=0
o=- 1645113374723125 1645113374723125 IN IP4 172.16.9.137
s=Media Presentation
e=NONE
b=AS:5050
t=0 0
a=control:rtsp://172.16.9.137:554/H264/ch1/sub/av_stream/?videoCodecType=H.264
m=video 0 RTP/AVP 96
c=IN IP4 0.0.0.0
b=AS:5000
a=recvonly
a=x-dimensions:704,576
a=control:rtsp://172.16.9.137:554/H264/ch1/sub/av_stream/trackID=1?videoCodecType=H.264
a=rtpmap:96 H264/90000
a=fmtp:96 profile-level-id=420029; packetization-mode=1; sprop-parameter-sets=Z00AHpY1QWAk03AQEBQAABwgAAV+QBA=,aO48gA==
a=Media_header:MEDIAINFO=494D4B48010300000400000100000000000000000000000000000000000000000000000000000000;
a=appversion:1.0

2022/02/17 15:56:33 track 0 is H264
2022/02/17 15:56:33 Setup:rtsp://syld:sdym1234@172.16.9.137:554/H264/ch1/sub/av_stream/ error:bad status code: 500 (Internal Server Error)

上面是日志，有可能是什么情况？

**Comment by langhuihui** [comment]
你试一下用其他播放器拉流看看会不会有问题
