### ISSUE TITLE
RTSP H265的流倒是能够添加成功，但是无法播放，

### ISSUE THREAD

**Issue by jyy007008** [Monibuca/plugin-rtsp#22]
服务信息如下：
2022/04/09 16:05:58 install plugin GateWay v3.0.13
2022/04/09 16:05:58 install plugin GB28181 v3.0.7
2022/04/09 16:05:58 install plugin HDL v3.0.7
2022/04/09 16:05:58 install plugin TS v3.0.1
2022/04/09 16:05:58 install plugin HLS v3.0.6
2022/04/09 16:05:58 install plugin Jessica v3.0.0
2022/04/09 16:05:58 install plugin LogRotate v3.0.0
2022/04/09 16:05:58 install plugin Record v3.0.0
2022/04/09 16:05:58 install plugin RTMP v3.0.3
2022/04/09 16:05:58 install plugin RTSP v3.0.8
2022/04/09 16:05:58 install plugin Summary v1.0.0
2022/04/09 16:05:58 install plugin WebRTC v3.0.3
2022/04/09 16:05:58 Ⓜ starting m7s  v3.5.1
2022/04/09 16:05:59 server gb28181 start at 192.168.1.120:5060
start udp server at:  :5060
2022/04/09 16:05:59 Jessica start reuse gateway port
2022/04/09 16:05:59 server gateway start at  :8081 :8082
2022/04/09 16:05:59 server rtmp start at :1935
2022/04/09 16:05:59 HDL start reuse gateway port
2022/04/09 16:05:59 udp server start listen video port[58200]
对应流的部分信息。
{
    "VideoTracks": {
        "h265": {
            "CodecID": 12,
            "PacketCount": 351,
            "BPS": 0,
            "SPSInfo": {
                "ProfileIdc": 0,
                "LevelIdc": 0,
                "MbWidth": 0,
                "MbHeight": 0,
                "CropLeft": 0,
                "CropRight": 0,
                "CropTop": 0,
                "CropBottom": 0,
                "Width": 1920,
                "Height": 1080
            },
            "GOP": 0,
            "UsingDonlField": false
        }
    },
    "AudioTracks": {
        "pcma": {
            "CodecID": 7,
            "PacketCount": 13959,
            "BPS": 8000,
            "SoundRate": 8000,
            "SoundSize": 16,
            "Channels": 1
        }
    },
    "DataTracks": {},
    "AutoCloseAfter": -1,
    "Transcoding": null,
    "ExtraProp": {
        "Transport": 2
    },
    "AppName": "live",
    "StreamName": "test002"
}
![image](https://user-images.githubusercontent.com/14024625/162563725-7a4a68ec-9f88-4ab2-b923-ae51a332aa5b.png)

**Comment by jyy007008** [comment]
![image](https://user-images.githubusercontent.com/14024625/162563881-b4b74b7d-9697-4876-81d6-bddc4f28b712.png)

**Comment by jyy007008** [comment]
"StreamName": "test002" 而图中却是test001,是我重启服务重新添加流导致的，可以忽略，流还是一个流

**Comment by langhuihui** [comment]
使用v4就可以了
