### ISSUE TITLE
RSTP拉流报错

### ISSUE THREAD

**Issue by sharfy** [Monibuca/plugin-rtsp#23]
2022/04/23 09:59:55 track 0 is H264
2022/04/23 09:59:55 track 1 is PCMA
2022/04/23 09:59:55 RTSP/1.0 200 OK
CSeq: 3
Server: Dahua Rtsp Server/2.0
Session: 866319148580;timeout=60
Transport: RTP/AVP/TCP;unicast;interleaved=0-1;ssrc=0006DBFD
X-Dynamic-Rate: 1

2022/04/23 09:59:55 RTSP/1.0 200 OK
CSeq: 4
Server: Dahua Rtsp Server/2.0
Session: 866319148580;timeout=60
Transport: RTP/AVP/TCP;unicast;interleaved=2-3;ssrc=0006DBFF
X-Dynamic-Rate: 1

2022/04/23 09:59:55 RTSP/1.0 200 OK
CSeq: 5
RTP-Info: url=trackID=0;seq=27277;rtptime=27214200;ssrc=0006DBFD,url=trackID=1;seq=7557;rtptime=2418728;ssrc=0006DBFF
Range: npt=0.000000-
Server: Dahua Rtsp Server/2.0
Session: 866319148580

2022/04/23 09:59:55 timestamp wrong live/test lastTs:40 currentTs:1

**Comment by langhuihui** [comment]
用新版本再试一下
