### ISSUE TITLE
RTSP 从远程拉取rtsp到m7s中API报错

### ISSUE THREAD

**Issue by HaoqiLi025** [Monibuca/plugin-rtsp#24]
当请求rtsp/api/pull时，如果传入save参数为true，程序报错：
<img width="969" alt="image" src="https://user-images.githubusercontent.com/29673415/178432839-02648732-6f5a-413e-a391-e7b76f7da51e.png">

**Comment by langhuihui** [comment]
已定位问题（在engine中），下一个版本修复
