### ISSUE TITLE
RTSP拉取已关闭流，程序崩溃

### ISSUE THREAD

**Issue by HaoqiLi025** [Monibuca/plugin-rtsp#25]
1、请求rtsp/api/pull，拉取远端流到引擎
2、请求api/closestream关闭流
3、再次请求1中添加的流。
程序崩溃：
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/29673415/178441514-46d64560-3ac0-4d87-b2bc-25be3af471c1.png">

**Comment by langhuihui** [comment]
应该已经修复了
