### ISSUE TITLE
拉流协议增加配置项  固定按TCP或UDP进行。

### ISSUE THREAD

**Issue by FireTiger23** [Monibuca/plugin-rtsp#26]
![77394a878efd95be86b0ae23c8ca3a9](https://user-images.githubusercontent.com/6301010/179886007-346cd53e-eb7e-48c2-9e3d-b622a7a1b0f2.jpg)
走UDP的时候 如果网络复杂 会出现花屏的情况。能否增加从配置文件来设置走哪种协议进行传输。

**Comment by langhuihui** [comment]
我来加个配置

**Comment by langhuihui** [comment]
我加了一个配置pullprotocol 不配置的话就是原来的逻辑，配置的话可以配成tcp或者udp，就强制使用

**Comment by FireTiger23** [comment]
谢谢~~~
