### ISSUE TITLE
当视频流中出现非音视频轨时会奔溃

### ISSUE THREAD

**Issue by FireTiger23** [Monibuca/plugin-rtsp#27]
![3becdfdb6586eff42bc998e4d1b6f14](https://user-images.githubusercontent.com/6301010/180125815-f410bae9-4d73-4575-b576-8d66c26dd0be.jpg)
![80cbca5661c8fabf467af51bc97ae80](https://user-images.githubusercontent.com/6301010/180125839-13cf7f74-e131-4cb6-9f35-376534ced06b.jpg)

如上图所示。

**Comment by langhuihui** [comment]
我加一个判断吧

**Comment by FireTiger23** [comment]
6666~~~
