### ISSUE TITLE
publisher.go 66,67行

### ISSUE THREAD

**Issue by Vitamin-Jin** [Monibuca/plugin-rtsp#28]
`vt.WriteSlice(common.NALUSlice{t.SPS})
vt.WriteSlice(common.NALUSlice{t.PPS})
`
publisher.go 66,67行，报错:无法将 't.SPS' (类型 func() []byte) 用作类型 []byte。

需修改为
`vt.WriteSlice(common.NALUSlice{t.SPS()})
vt.WriteSlice(common.NALUSlice{t.PPS()})
`

**Comment by Vitamin-Jin** [comment]
依赖包版本变了，要修改的还有很多。

**Comment by langhuihui** [comment]
不对吧
