### ISSUE TITLE
client.go的60行IDE提示错误

### ISSUE THREAD

**Issue by myahuang** [Monibuca/plugin-rtsp#29]
p.tracks = tracks，goland编辑器把鼠标放在后面的tracks报错Cannot use 'tracks' (type Tracks) as the type []*clientTrack，我分析的确如此，另外p.tracks这种引入另外包字段的方法也报错，go对于这种情况不是应该首字母都是大写字母吗？

问题是这种编辑器报错的程序，为什么运行能通过，我测试发现语句执行了，不报错

**Comment by langhuihui** [comment]
goland对有一些语法支持的不是很好，建议用vscode
