### ISSUE TITLE
添加RTSP拉流转发的时候，一会拉流转发就自动停止删除了

### ISSUE THREAD

**Issue by langmansh** [Monibuca/plugin-rtsp#3]
场景：直接启动monica项目

问题：直接在RTSP中添加拉流转发的摄像机RTSP地址，随后接收了一段时间立马就被删除了，服务端提示timeout超时。如果我添加第二个RTSP地址，第一个立马就停掉了，依此类推。哪怕只添加一个一段时间也超时了。

这个是什么原因导致的呢。

**Comment by langhuihui** [comment]
你用最新版试试
