### ISSUE TITLE
RTSP拉流API无法拉取音频

### ISSUE THREAD

**Issue by SundayGoGo** [Monibuca/plugin-rtsp#33]
使用rtsp/api/pull?target=[RTSP地址]&streamPath=[流标识] 拉取远端流到m7s，使用ffplay播放时无法播放声音
<img width="503" alt="image" src="https://user-images.githubusercontent.com/26375737/219829135-754fb287-5583-4fc6-bc0b-232397126e25.png">

**Comment by langhuihui** [comment]
试试最新版本
