### ISSUE TITLE
请教一下引入rtsp插件却无法推流

### ISSUE THREAD

**Issue by KEIONG** [Monibuca/plugin-rtsp#35]
日志中显示成功install rtsp插件和rtmp插件。  但是只有“server rtmp start at	{"plugin": "RTMP", "listen addr": ":1935"} ”这一条日志。  没有rtsp的服务启动日志， 想问一下复合预期吗

**Comment by langhuihui** [comment]
对rtsp启动没有打日志出来

**Comment by KEIONG** [comment]
> 对rtsp启动没有打日志出来
那应该是我推流测的问题 所以理论上来说 引入依赖 启动就可以推流了吗？ 很抱歉这么低级的问题开一个issue

**Comment by langhuihui** [comment]
对，如果有问题会有日志的

**Comment by KEIONG** [comment]
> 对，如果有问题会有日志的

谢谢
