### ISSUE TITLE
rtsp pull接口的一个疑问？

### ISSUE THREAD

**Issue by YoooDT** [Monibuca/plugin-rtsp#43]
如果创建相同的streamPath，一直创建，gortsp的协程是不是没有回收啊。用pprof看协程数一直增加。

**Comment by langhuihui** [comment]
你是怎么操作的呢

**Comment by YoooDT** [comment]
> 你是怎么操作的呢

/rtsp/api/pull接口  多次调用。 streamPath都填live/1,target也是同一个rtsp流

**Comment by langhuihui** [comment]
日志可以发出来给我看看吗？

**Comment by langhuihui** [comment]
此问题已经修复
